CREATE TABLE users (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  status TINYINT(255) NOT NULL UNSIGNED,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  PRIMARY KEY id
  );